\documentclass{beamer}\usetheme{boxes}

\usepackage{amsmath,hyperref}

\newcommand{\Mp}{\ensuremath{{M_{+}}}}
\newcommand{\barMp}{\ensuremath{\overline{\Mp}}}
\newcommand{\Dt}{\ensuremath{\Delta t}}
\newcommand{\tM}[1]{\ensuremath{\tilde{M}(#1)}}
\newcommand{\tMt}{\tM{\tau}}
\newcommand{\tMB}{\ensuremath{{\tilde{M}_B}}}
\newcommand{\tE}[1]{\ensuremath{{\tilde{E}(#1)}}}
\newcommand{\tEt}{\tE{\tau}}

\newcommand{\bskip}{\\~\\}

\newcommand{\checkitem}{\item[\Checkmark]}
\newcommand{\xitem}{\item[\XSolidBrush]}
\newcommand{\mehitem}{\item[$\approx$]}
\newcommand{\easyframe}[2]{\frame{\frametitle{#1}
#2
}}

\setbeamertemplate{frametitle}[default][center]

\begin{document}
\SweaveOpts{concordance=TRUE}
\title{Simulating Meth Production Networks}
\author{Carl~A.~B.~Pearson\inst{1} \and Burton~H.~Singer\inst{1} \and David~A.~Bright\inst{2}}
\institute{Emerging Pathogens Institute, University of Florida\inst{1} \and School of Social Sciences, University of New South Wales\inst{2}}
\date{19 FEB 14}
\frame{\titlepage}

\usebackgroundtemplate{
\vbox to \paperheight{\vfil\hbox to \paperwidth{\hfil\includegraphics[width=0.7\paperheight,height=0.7\paperheight]{2012army.png}\hfil}\vfil} }
\frame{
\frametitle{Supported by ARO Award \#W911NF-11-1-0036Z}
}
\usebackgroundtemplate{}

\easyframe{Overview}{

\begin{description}
\item[Network Problems] what goes in (a simulation) is what comes out
\item[A Meth Bust ``Network''] circa 70s Australia
\item[Simulating Production] Breaking Bad?
\item[Next Steps] Observation Model, Intervention Outcomes, Competition, Adaptation

\end{description}
% notes-notes-notes
}

\easyframe{NETWORKS ARE NOT THE PHENOMENA}{
\begin{itemize}
\item<2-> What is? Context dependent.
\item<3-> What do we observe? Interaction events, environmental changes.
\item<4-> A network is a representation
\item<5-> For some cases: that's useful - can reliably observe events, translate to network, calculate property with predictive power relative to some future outcome
\item<6-> For ``dark'' networks - highly questionable
\end{itemize}

% In, say, a school setting let's imagine I'm "popular" (clearly not historically accurate).
% The phenomena is not that I say I'm friends with a lot of people, and that they agree -
% it is that I get preferential treatment in this context.  That treatment may correlate with
% some calculated property of the network based on friendship network for some specific context
%
% 
}

% transition: let's consider an example dark network

\easyframe{PROSECUTED METH PRODUCTION \&\ DISTRIBUTION GROUP}{
TODO: INSERT PLOT AS BACKGROUND
\begin{itemize}
\item<2-> individuals convicted, connected by association, from public record prosecutorial data
\item<3-> how might this data be flawed?
\item<4-> if we take this as the model, even after adding roles, what do we know is unrepresented?
\item<5-> given those issues: does simulation on this network -- which includes deriving network statistics and predictions from them -- make sense?
\end{itemize}
}

\easyframe{SIMULATING METH PRODUCTION}{
\begin{block}{AKA, answer the last question formally}
\begin{itemize}
\item<2-> Prosecution data hypothesize roles
\item<3-> use as basis for mechanical description
\item<4-> simulate that enterprise
\item<5-> compare measures -- pseudoephedrine consumption, methamphetamine production, net profit rates -- to available estimates
\end{itemize}
\end{block}

}

\setbeamercovered{transparent}
\easyframe{SIMULATING METH PRODUCTION}{
\begin{block}{Relatively few parts, all written in Scala}
\begin{description}
\item[\texttt{World}]<2> meth consumption rate, pseudo cost 
\item[\texttt{Supplier}s, \texttt{Retailer}s, \texttt{Wholesaler}]<3> margins and purchase or delivery efficiencies
\item[\texttt{Middleman}]<4> margin, efficiency
\item[\texttt{Cook}]<5> margin, pseudo conversion efficiency
\end{description}
\end{block}
\begin{block}{SIMPLE ECONOMIC FORCES ONLY}
Agents try to net their margin per iteration.  Demand for meth inelastic.  No economies of scale.
\end{block}
}
\setbeamercovered{}

\easyframe{PARAMETER ESTIMATES\cite{gong2012profitable}\cite{mcketin2005estimating}\cite{ritter2012evaluating}\cite{australian2008australiancrime}}{
Use kilograms as reference mass unit, AUS \$\ as reference price unit
\begin{description}
\item[Unit Meth per Unit Pseudo] 0.9
\item[Meth Conversion Efficiency] 0.5 - 1.0
\item[Meth Consumption] average 10 doses per user per month, 0.0001 units per dose, 20 users per capita
\item[thing] margins and purchase or delivery efficiencies
\item[\texttt{Middleman}] margin, efficiency
\item[\texttt{Cook}] margin, pseudo conversion efficiency
\end{description}
}

\setbeamercovered{transparent}
\easyframe{STEADY STATE RESULTS}{
\begin{description}
\item[Street Price]<1>X per dose vs observed Y per dose
\item[Gang Takehome]<2>X per month vs observed Y per month
\end{description}
}
\setbeamercovered{}

\easyframe{PERTURBATIONS}{
TODO series of background plots
\begin{description}
\item Increase Pseudo Cost at time T
\item Increase Demand at time T
\item Increase Margins at time T
\item Decrease efficiencies at time T
\end{description}
}

\easyframe{TODO}{
\begin{block}{Next Steps}\begin{itemize}
\item[Observation Model] translate simulate outputs via filter to observations
\item[Group Dynamics] intra- and intergroup competition, turnover of employees, customers 
\item[Intervention Outcomes] single gang interventions, evolution of competing gangs
\end{itemize}
\end{block}
}

\easyframe{QUESTIONS?}{
talk and simulation source available at \\~\\
https://github.com/pearsonca/sunbelt-2014 \\~\\
https://github.com/pearsonca/scala-commsim
}

\easyframe{REFERENCES}{
\footnotesize
\bibliography{biblio}{}
\bibliographystyle{plain}
}

\easyframe{SUPPORTING MATERIAL}{
\begin{block}{Meth Consumption}
100 mg per dose; per capita: roughly 10 ``regular'' users (between weekly and monthly dose), roughly 10 ``dependent'' users
\end{block}
}

\end{document}